# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "furyu_blog_sample"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.4.2/centos64-x86_64-20140116.box"

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :public_network

  config.ssh.forward_agent = true

  config.vm.synced_folder "..", "/playbook"
  
  config.vm.provision :shell, :path => "bootstrap.sh"
end
